[package]
name = "bpx-api-types"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
